# Enhanced Master's Thesis: Comprehensive Federated Learning Analysis Configuration

# Experiment metadata
experiment_name: "comprehensive_fl_thesis_analysis"
description: "Master's thesis comprehensive analysis of federated learning algorithms across multiple challenges"
author: "Mehdi MOUALIM"
thesis_title: "Comparative Analysis of Federated Learning Algorithms: Performance, Efficiency, and Fairness"

# Algorithms to test - comprehensive comparison
algorithms:
  - "FedAvg"
  - "FedProx"
  # Add more algorithms as needed:
  # - "FedAdam"
  # - "SCAFFOLD"
  # - "COOP"

# Algorithm-specific parameters for fair comparison
algorithm_params:
  fedavg: {}
  fedprox:
    mu: 0.01  # Proximal term coefficient
  fedadam:
    beta1: 0.9
    beta2: 0.999
    tau: 0.001  # Server learning rate
  scaffold:
    learning_rate_server: 1.0
    control_variate: true
  coop:
    alpha: 0.1  # Cooperation weight
    beta: 0.1   # Regularization weight

# Datasets for comprehensive evaluation
datasets:
  - "mnist"
  # Add more datasets as needed:
  # - "cifar10"
  # - "femnist"

# Data distribution settings - heterogeneity challenge
data_distributions:
  
  - "non_iid"

# Heterogeneity levels (Dirichlet concentration parameter)
# Lower beta = more heterogeneous (more challenging)
# Higher beta = more homogeneous (easier)
beta_values: [0.1,1.0]  # 0.1=high heterogeneity, 1.0=moderate heterogeneity

# Federation configuration
num_clients: 2
clients_per_round: 1
num_rounds: 2
local_epochs: 3

# Model and training configuration
learning_rate: 0.01
batch_size: 32
weight_decay: 1e-4

# Enhanced Academic Research Settings
academic_analysis:
  statistical_testing: true
  confidence_level: 0.95
  effect_size_analysis: true
  power_analysis: true
  
# Research Question Specific Settings
research_questions:
  fl_vs_centralized: true  # Compare FL to centralized learning
  non_iid_impact: true     # Analyze heterogeneity impact
  device_reliability: true # Test device dropout scenarios
  communication_efficiency: true
  privacy_vs_accuracy: true
  scalability_analysis: true

# Privacy challenge settings
differential_privacy: false  # Set to true for privacy analysis
dp_epsilon: 1.0
dp_delta: 1e-5
dp_noise_multiplier: 1.0
dp_max_grad_norm: 1.0

# Communication challenge settings
compression: false
quantization: false
sparsification: false

# Enhanced Robustness Testing
robustness_testing:
  dropout_simulation: true
  dropout_rates: [0.0, 0.1, 0.2, 0.3]
  irregular_participation: true

# Evaluation settings
target_accuracy: 0.99
early_stopping: true
early_stopping_patience: 15

# Output configuration
save_results: true
save_models: false
output_dir: "results"
generate_plots: true
generate_dashboard: true
generate_report: true

# Enhanced Academic Output Settings
academic_outputs:
  generate_latex_tables: true
  generate_presentation_plots: true
  generate_statistical_reports: true
  generate_interactive_dashboards: true
  save_raw_data_csv: true

# Statistical analysis
num_runs: 1  # Multiple runs for statistical validity
confidence_interval: 0.95
statistical_tests: true

# System settings
random_seed: 42
device: "auto"  # "cpu", "cuda", or "auto"
num_workers: 4
pin_memory: true

# Thesis-specific settings
thesis_mode: true
detailed_logging: true
verbose_output: true